theme = "lanyon-hugo"
baseURL = "/Hippocamplus/"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.RData", "\\.gz$"]
publishDir = "docs"

[params]
title = "Hippocamplus"
tagline = 'My Second Memory'
description = 'A place to gather useful information I keep on forgetting.'
year = "2017"
[params.github]
url = "https://github.com/jmonlong"

[permalinks]
post = "/:year/:month/:day/:slug/"
fixed = ":slug/"
